import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Busca Cep',
  description: 'Generated by Busca Cep',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <Navbar />{children}</body>
    </html>
  )
}
